# Generated by Django 3.2.7 on 2021-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
